// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPIPostgresSqlCSS.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalAPIPostgresSqlCSS.Migrations
{
    [DbContext(typeof(CSSDb))]
    [Migration("20221121193941_migrationtest")]
    partial class migrationtest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.Admins", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Admin_Email")
                        .HasColumnType("text");

                    b.Property<string>("Admin_Password")
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.Commands", b =>
                {
                    b.Property<int>("Command_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Command_Id"));

                    b.Property<int?>("AdminsUser_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Command_Performed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Command_Read")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Command_Received")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Command_String")
                        .HasColumnType("text");

                    b.Property<string>("Command_Value")
                        .HasColumnType("text");

                    b.Property<int?>("Duplicate_Flag")
                        .HasColumnType("integer");

                    b.Property<int?>("Log_Id")
                        .HasColumnType("integer");

                    b.HasKey("Command_Id");

                    b.HasIndex("AdminsUser_Id");

                    b.HasIndex("Log_Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.EnvironmentalData", b =>
                {
                    b.Property<int>("Entry_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Entry_Id"));

                    b.Property<float?>("Humidity")
                        .HasColumnType("real");

                    b.Property<float?>("Light")
                        .HasColumnType("real");

                    b.Property<int?>("Pictures_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Reservoir_Water_Level")
                        .HasColumnType("text");

                    b.Property<float?>("Soil_Moisture_1")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_2")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_3")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_4")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_5")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_6")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_7")
                        .HasColumnType("real");

                    b.Property<float?>("Soil_Moisture_8")
                        .HasColumnType("real");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamps")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float?>("Water_Level")
                        .HasColumnType("real");

                    b.HasKey("Entry_Id");

                    b.HasIndex("Pictures_Id");

                    b.ToTable("EnvironmentalData");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.Logs", b =>
                {
                    b.Property<int>("Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Log_Id"));

                    b.Property<string>("Log_Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamps")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Log_Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.Pictures", b =>
                {
                    b.Property<int>("Pic_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pic_Id"));

                    b.Property<string>("Camera_Pic_Path_1")
                        .HasColumnType("text");

                    b.Property<string>("Camera_Pic_Path_2")
                        .HasColumnType("text");

                    b.Property<string>("Camera_Pic_Path_3")
                        .HasColumnType("text");

                    b.Property<string>("Camera_Pic_Path_4")
                        .HasColumnType("text");

                    b.Property<float?>("Classification_Accurracy_1")
                        .HasColumnType("real");

                    b.Property<float?>("Classification_Accurracy_2")
                        .HasColumnType("real");

                    b.Property<float?>("Classification_Accurracy_3")
                        .HasColumnType("real");

                    b.Property<float?>("Classification_Accurracy_4")
                        .HasColumnType("real");

                    b.Property<int?>("Classification_Id_1")
                        .HasColumnType("integer");

                    b.Property<int?>("Classification_Id_2")
                        .HasColumnType("integer");

                    b.Property<int?>("Classification_Id_3")
                        .HasColumnType("integer");

                    b.Property<int?>("Classification_Id_4")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamps")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Pic_Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.Commands", b =>
                {
                    b.HasOne("MinimalAPIPostgresSqlCSS.Models.Admins", "Admins")
                        .WithMany("Commands")
                        .HasForeignKey("AdminsUser_Id");

                    b.HasOne("MinimalAPIPostgresSqlCSS.Models.Logs", "Logs")
                        .WithMany()
                        .HasForeignKey("Log_Id");

                    b.Navigation("Admins");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.EnvironmentalData", b =>
                {
                    b.HasOne("MinimalAPIPostgresSqlCSS.Models.Pictures", "Pictures")
                        .WithMany()
                        .HasForeignKey("Pictures_Id");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("MinimalAPIPostgresSqlCSS.Models.Admins", b =>
                {
                    b.Navigation("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
